version: '3'
services:
  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=seu_token_de_acesso
      - TZ=America/Sao_Paulo  # Altere o fuso horário conforme necessário
